name: Transition Jira Ticket on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  transition-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira ticket key from PR title
        id: extract
        run: |
          title="${{ github.event.pull_request.title }}"
          branch="${{ github.event.pull_request.head.ref }}"
          echo "Title: $title"
          echo "Branch: $branch"
          
          ticket=$(echo "$title $branch" | grep -oE '[A-Z]+-[0-9]+' | head -n1 || true)
          
          if [ -z "$ticket" ]; then
            echo "No Jira ticket found in PR title or branch name"
            echo "ticket=" >> $GITHUB_OUTPUT
          else
            echo "Found Jira ticket: $ticket"
            echo "ticket=$ticket" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Jira transition
        run: |
          curl -X POST \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"transition": {"id": "41"}}' \
            "https://spendflo-team-ipj50y3n.atlassian.net/rest/api/3/issue/${{ steps.extract.outputs.ticket }}/transitions"
