name: Transition Jira Ticket on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  transition-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira ticket key from PR title
        id: extract
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          ticket=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
          echo "ticket=$ticket" >> $GITHUB_OUTPUT

      - name: Trigger Jira transition
        run: |
          curl -X POST \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"transition": {"id": "41"}}' \
            "https://spendflo-team-ipj50y3n.atlassian.net/rest/api/3/issue/${{ steps.extract.outputs.ticket }}/transitions"
